### ISSUE TITLE
关于性能优化的那个项目

### ISSUE THREAD

**Issue by YGAS** [coderZsq/coderZsq.project.oc#2]
性能优化后的界面会有明显的虚化
![image](https://user-images.githubusercontent.com/1214708/42939393-1272a622-8b88-11e8-8fa8-ccd325fda04c.png)
![image](https://user-images.githubusercontent.com/1214708/42939401-1b3424a2-8b88-11e8-8b56-1761c077a4be.png)

**Comment by coderZsq** [comment]
已经解决
